export type LeaderboardEntry = {
  gamertag: string;
  kd: number;
};

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { gamertag: "Sn1per_99", kd: 3.84 },
  { gamertag: "GhostMode", kd: 3.42 },
  { gamertag: "KillCam_X", kd: 3.18 },
  { gamertag: "NoScope420", kd: 2.47 },
  { gamertag: "V0idWalker", kd: 2.31 },
  { gamertag: "Th3Reaper", kd: 2.18 },
  { gamertag: "ApexHusky", kd: 2.05 },
  { gamertag: "Cr1msonFox", kd: 1.92 },
  { gamertag: "ZeroChill_88", kd: 1.78 },
  { gamertag: "ShadowDrip", kd: 1.66 },
  { gamertag: "PixelHavoc", kd: 1.59 },
  { gamertag: "NightOwl_77", kd: 1.54 },
  { gamertag: "BlitzCore", kd: 1.51 },
  { gamertag: "WarFr0g", kd: 1.42 },
  { gamertag: "Quasar_X9", kd: 1.38 },
  { gamertag: "Tac_Tical", kd: 1.35 },
  { gamertag: "Reflex_Rae", kd: 1.32 },
  { gamertag: "AceOf3pades", kd: 1.29 },
  { gamertag: "NeoBlaze", kd: 1.26 },
  { gamertag: "CryoNova", kd: 1.22 },
  { gamertag: "DvilGrin", kd: 1.19 },
  { gamertag: "Th3Specter", kd: 1.16 },
  { gamertag: "SilentEcho_42", kd: 1.13 },
  { gamertag: "Vortex_K", kd: 1.10 },
  { gamertag: "NovaPulse", kd: 1.08 },
  { gamertag: "RogueTr1gger", kd: 1.06 },
  { gamertag: "Frostb1te", kd: 1.04 },
  { gamertag: "SkyHook_88", kd: 1.02 },
  { gamertag: "Drift3rPro", kd: 1.0 },
  { gamertag: "WildKard_X", kd: 0.98 },
  { gamertag: "Scope_Slayer", kd: 0.96 },
  { gamertag: "PrettyKaos", kd: 0.94 },
  { gamertag: "NightShift_99", kd: 0.92 },
  { gamertag: "SmokeStack", kd: 0.9 },
  { gamertag: "KingPin_K9", kd: 0.89 },
  { gamertag: "Stratos_Mvp", kd: 0.88 },
  { gamertag: "Pulse_Rider", kd: 0.86 },
  { gamertag: "Hollow_Hunter", kd: 0.85 },
  { gamertag: "Ironclad_88", kd: 0.84 },
  { gamertag: "Velocity_X", kd: 0.83 },
  { gamertag: "EchoFox_07", kd: 0.82 },
  { gamertag: "Th3LastL1ne", kd: 0.81 },
  { gamertag: "Ranger_Bolt", kd: 0.8 },
  { gamertag: "CmdrSnake", kd: 0.79 },
  { gamertag: "Diabl0_R", kd: 0.78 },
  { gamertag: "CalmFury", kd: 0.77 },
  { gamertag: "Spectre_99", kd: 0.76 },
  { gamertag: "Bl1tzkr1eg", kd: 0.75 },
  { gamertag: "Ghost_Stack", kd: 0.73 },
  { gamertag: "RookiePunch", kd: 0.71 },
];
